version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    container_name: db-sqlserver
    # Para simplificar esta prueba se deja la contraseña directamente.
    # Sin embargo lo recomendable es que pueda quedar como variable de entorno. 
    environment:
      MSSQL_SA_PASSWORD: "<YourStrong@Passw0rd>"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./scripts:/scripts
